spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travels?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 87654321

mybatis:
  type-aliases-package: com.lsh.sportplay
  mapper-locations: classpath:mapper/*.xml

server:
  port: 9000